### PR TITLE
Fix unclickable markers

### LINKED ISSUE #7: Sometimes clicking on the map doesn't work
I see this on both Firefox/Chrome, and on Chrome on Android. I consistently see this happen at the default zoom level near the Morning Parade Coffee location (Gerrard and Woodbine).

I did a bit of debugging, and click listeners don't fire on the `ReactMapGL` component at all when this happens (although adding a click listener to the `#container` element shows that firing).

Additionally, on desktop the cursor doesn't change to the pointer or grabber as expected in these cases. So maybe something wonky going on with the DOM?

### PR DESCRIPTION
**Pull request by foreverhomes**
### Description

The way that the position of the icons was being styled would make it possible for a marker's container to obstruct the clickable icon of another marker. The fix here is to apply the transform to the marker instead of the icon.

I also did some minor style cleanup using array destructuring for the response location values, turning them into named variables instead of accessing by index.

I _also_ added Styled Components, an issue we can discuss in this PR! It doesn't add a ton utility here but is, in my mind, the best way to move forward and can facilitate moving stuff away from the style prop and .css files. But it's not at all required for this fix - same could be accomplished with a second css class. 

Lastly, there was a security update that required the bump in `parcel-bundler`

(I can't see the map locally so actually just making this PR so I can see my changes, haha)

fixes #7 

### TODO

- [x] Fix selected pin styling
- [x] Decide on marker hover cursor style
- [x] Break up this PR into TBD.

### CODE REVIEW

**Comment by foreverhomes** [comment]
Screen Shot 2019-12-17 at 7 02 24 PM

😖

**Comment by leibovic** [comment]
We should figure out how to fix your dev environment!!

But I think you're seeing an issue I saw before, which is that updating parcel-bundler breaks react-map-gl 😢 I basically just punted on the security issue for now... I would try reverting that change to fix your issue.

**Comment by foreverhomes** [comment]
@leibovic that _did_ fix my local dev issues! Thanks for the hot tip.

**Comment by leibovic** [comment]
I filed an issue for us to track: https://github.com/leibovic/baby-in-tow/issues/14

As for this PR... I would be more comfortable if it was broken up, especially since I don't have any tests right now 😬 Although it wouldn't be too hard to thoroughly regression test with the deploy preview. I'll take a closer look tomorrow. Thanks for the fix!

**Comment by leibovic** [comment]
Just quickly testing now though... I noticed that the `cursor: pointer` style is missing from the map markers. Also the selected pin style isn't being rendered, so it seems like there's a bit more work to do.

But the clicking is consistently working at least!

**Comment by foreverhomes** [comment]
Indeed.

I do have one question re: the pointer - it seems to have been an intentional choice of the map library. They are using the hand cursor for being able to drag the map so transitioning from hand to pointer is super subtle. (I did hack it to work with `!important` boooo) so I'm wondering if we're sure we'd want to do this?

Re above: how would you like me to split up this PR? Happy to!

**Comment by foreverhomes** [comment]
The pin styling was super easy! I had just... forgot to re-pass in the `selected` prop. (which reminds me, I'm going to make an issue to add PropTypes and enforce in ES Linting. Important!)

Screen Shot 2019-12-19 at 9 33 05 AM

File: src/Pin.js [hunk 1]
```diff
@@ -1,110 +1,103 @@
-import React, { PureComponent } from "react";
+import React from "react";
 
-export default class Pin extends PureComponent {
```
Comment (leibovic) [inline src/Pin.js]: Why did you update this to no longer be a `PureComponent`? To be fair, I just based this off example code from the map library, so I don't have any particular reason why I did that in the first place. Just want to understand if that was necessary for this fix.

File: src/Pin.js [hunk 2]
```diff
@@ -1,110 +1,103 @@
...
+const ICON_SELECTED_HEIGHT = 53;
 
-    return (
-      <svg
-        width={selected ? 47 : 30}
-        height={selected ? 53 : 36}
-        viewBox={selected ? "0 0 47 53" : "0 0 30 36"}
-        fill="none"
-        style={{
-          cursor: "pointer",
```
Comment (leibovic) [inline src/Pin.js]: Looks like this `cursor: "pointer"` style got dropped along the way - is that the reason I saw it's missing in the preview build?

**Comment by leibovic** [comment]
> I do have one question re: the pointer - it seems to have been an intentional choice of the map library. They are using the hand cursor for being able to drag the map so transitioning from hand to pointer is super subtle. (I did hack it to work with `!important` boooo) so I'm wondering if we're sure we'd want to do this?

I wonder what exactly is causing it, since it doesn't seem to be an issue with this example from the library (and also wasn't an issue before): https://uber.github.io/react-map-gl/#/Examples/markers-popups

I agree it's suspect to use !important. Previously I was setting the style directly on the svg, and it looks like that was removed in your change - was that intentional?

> Re above: how would you like me to split up this PR? Happy to!

It's okay, I don't want to cause extra work for you if this is working now, and the main thing I would have split out (the parcel-bundler update) is already taken care of. I'll leave some review comments mentioning things I probably would have kept separate. My main concern is just that it's harder to review the bug fix when there are a lot of other changes included as well, and if there's a regression it will be hard to tell what caused it 🙂

File: src/Marker.js [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+    ` : css`
+      transform: translate(-15px,-36px);
+    `
+  };
+`;
+
+export const Marker = ({ selected, latitude, longitude, category, onMarkerClick }) => {
+  const pinColor = category
+    ? categoryColors[category].backgroundColor
+    : 'white';
```
Comment (leibovic) [inline src/Marker.js]: With this change markers now know about categories... my original intention was to keep that knowledge restricted to `App.js`. It doesn't seem like a big deal to make it globally accessible. Although it does feel out of the scope of this bug fix.

File: src/App.js [hunk 4]
```diff
@@ -71,26 +67,45 @@ const App = ({ locationId }) => {
...
+          stroller,
+          changeTable,
+          indoor,
+          outdoor,
+          description,
+          strollerTips,
+          nursingTips,
+          website,
+          instagram,
+          facebook,
```
Comment (leibovic) [inline src/App.js]: This is a small cleanup I would have made separate. I agree this is nicer, but also an accidental mistake here would have the potential to totally bust the data of the app if the order is wrong. Although I do really like this change! This will help avoid errors if we ever add a new column in the middle (vs. needing to update all the indices on all the lines... literally a bug happened previously when I made a typo doing that once).

**Review by leibovic — APPROVED** [review]
I'd like to just figure out that missing `cursor: "pointer"` issue before merging this - but otherwise thank you so much!!! 🙌

**Comment by leibovic** [comment]
Oh another comment - I checked out your branch to test things out locally, and it looks like your text editor must not have been set to format with the Prettier settings for the repo (just using the default Prettier config), because a bunch of things changed when I saved the files. Is this something that would normally be configured in CI? I've just been relying on my editor to do it, but would be good to make sure that's not an issue if more people are contributing.

File: src/Pin.js (hunk 2 above)
Comment (leibovic) [reply src/Pin.js]: I feel like the library unintentionally is paving over cursor styles passed in:
https://github.com/uber/react-map-gl/blob/5.1-release/src/components/marker.js#L92

And they're just relying on setting the style directly on the child passed in. For reference, this is the example I was using for guidance when building this: https://github.com/uber/react-map-gl/blob/5.1-release/examples/controls/src/city-pin.js

File: src/App.js (hunk 4 above)
Comment (foreverhomes) [reply src/App.js]: Yeah that makes sense. I ended up doing it in this PR because I needed to follow the flow of the lat/lon props.

File: src/Pin.js (hunk 1 above)
Comment (foreverhomes) [reply src/Pin.js]: It removes an extra dependency and accomplishes the same thing! PureComponent just re-renders on props change no matter what, i.e. a plain ol' function component.

**Comment by foreverhomes** [comment]
Re: prettier - I don't have auto-format on save on because it can be the worst (i.e. widget runner updates). We should add husky as a dev dependency and have it run a pre-commit hook that prettifies any stages files. (and could also lint them at the same time if we want! this is what we do for league web.

File: src/Marker.js (hunk 3 above)
Comment (foreverhomes) [reply src/Marker.js]: I could hoist this back up to App.js pretty easily, I think! And would remove this dependency on the component, which is also good.

File: src/Pin.js (hunk 2 above)
Comment (foreverhomes) [reply src/Pin.js]: I see! I ended up just adding a `svg` selector to the styled component css and it restored the correct cursor: pointer style. Thanks!

**Comment by foreverhomes** [comment]
@leibovic The preview deploy looks good but would like you to double approve before I send to master. Will be nice to have some tests in place soon so I don't have to be so antsy!

**Comment by leibovic** [comment]
Thanks so much! I just went through the preview build and it looks great. Also I'm okay being on call to fix any regressions if users report them 😜
